### ISSUE TITLE
Cannot resolve symbol UnderlyingUsbCommunication.USB_REQUEST_ASYNC);

### ISSUE THREAD

**Issue by SvenSv** [magnusja/libaums#107]
is what I get when I try to set the underlying usb communication:
          UsbCommunicationFactory.setUnderlyingUsbCommunication(UnderlyingUsbCommunication.USB_REQUEST_ASYNC);

When I try to import it manually, it says "Is not public, cannot be accessed from outside the package".

**Comment by magnusja** [comment]
Thanks for reporting. Made it public, have a look at develop branch.
