### ISSUE TITLE
React Native Port

### ISSUE THREAD

**Issue by joshuajtaylor** [magnusja/libaums#109]
@magnusja This is not really an issue but more of a request for permission as I could not find a way to contact the contributors directly. First, thank you for such a useful library. I used this **_great_** library in a ReactNative app that most likely will not be released/used. But I would like to put the ReactNative module I created that interfaces with this library on GitHub for others to use. Please let me know if you have any concerns.

**Comment by magnusja** [comment]
Hey,
sure that is certainly fine with me. Maybe you can post a link here, then I will include it in my README for interested people.
Thanks.
