### ISSUE TITLE
usb format

### ISSUE THREAD

**Issue by XIONG-WEN** [magnusja/libaums#111]
Hi, Excuse me.
How to format Usb.

**Comment by magnusja** [comment]
Hey there,
this is currently not implemented and I have no intention to add that.

**Comment by XIONG-WEN** [comment]
Thank you for reply.
Could you help to share some ideas for me?

**Comment by magnusja** [comment]
If you really want to be able to format a USB drive on your phone have a look here: https://github.com/waldheinz/fat32-lib/blob/master/src/main/java/de/waldheinz/fs/fat/SuperFloppyFormatter.java
