### ISSUE TITLE
Error:Project :httpserver declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :libaums.

### ISSUE THREAD

**Issue by dcmcshan** [magnusja/libaums#117]
Apologies, if this is obvious. I'm not overly android savvy...

I get this error from within Android Studio.  Any advice on how to repair?  Thanks!

Error:Project :httpserver declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :libaums.

**Comment by magnusja** [comment]
I have never seen this  are you trying the example app or are you including the libraries through Gradle in your project?

**Comment by dcmcshan** [comment]
I literally just opened the app/build.gradle in Android Studio and it says “Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly”

**Comment by magnusja** [comment]
Try to open the top level `build.gradle` which is for the whole project (all modules).
