### ISSUE TITLE
Wrong type

### ISSUE THREAD

**Issue by graynote** [magnusja/libaums#119]
https://github.com/magnusja/libaums/blob/f8deff58fe07a3474f6a23e5c08f711d8c77ab25/libaums/src/main/java/com/github/mjdev/libaums/fs/fat32/FatDirectoryEntry.java#L477

final int msb = getUnsignedInt16(MSB_CLUSTER_OFF);

should be changed to 

final long msb = getUnsignedInt16(MSB_CLUSTER_OFF);

Negative value can be returned in current code. If msb has 0xFFFF, return value will be negative.

**Comment by magnusja** [comment]
Thanks for reporting this! Should be fixed in develop now :)
