### ISSUE TITLE
Error with Android Studio 3 nad new gradle

### ISSUE THREAD

**Issue by umarfrq92** [magnusja/libaums#135]
```Error while build apk development branch  Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex```

**Comment by magnusja** [comment]
Yep, I have that problem, too. Downgrading to Android Studio 2.x should work. I have not figured out yet what is wrong. So if you do please let me know.

**Comment by irsen001** [comment]
in module storageprovider, file build.gradle, Line:38, delete org.apache.commons:commons-io:1.3.2, and IOUtiols in ParcelFileDescriptorUtil.java, it will build ok in Android Studio 3x

**Comment by umarfrq92** [comment]
A failure occurred while executing com.android.build.gradle.internal.transforms.JacocoTransform$JacocoWorkerAction
in andriod studio 3.1

**Comment by Metske** [comment]
Add `        classpath 'org.codehaus.groovy:groovy-all:2.4.12'
        classpath('com.dicedmelon.gradle:jacoco-android:0.1.2'){
            exclude group: 'org.codehaus.groovy', module: 'groovy-all'
        }`
to build.gradle (Project: libaums-develop)
