### ISSUE TITLE
A failure occurred while executing com.android.build.gradle.internal.transforms.JacocoTransform$JacocoWorkerAction in andriod studio 3.1

### ISSUE THREAD

**Issue by umarfrq92** [magnusja/libaums#138]
PLEASE NOTE:
Before creating an issue, please think about wheter you are really reporting an issue or just have a question/problem. The latter are better suited for Stackoverflow or gitter (https://gitter.im/libaums). The best approach for a question or problem regarding libaums is to ask on Stackoverflow and hint me to the question via gitter!

If you are sure that you would like to open an issue, please delete all of this message and continue. 
Thank you!

**Comment by Metske** [comment]
Fixed by adding  `classpath 'org.codehaus.groovy:groovy-all:2.4.12'` to build.gradle (Project: libaums-develop)

**Comment by Ahmedbinyameen** [comment]
Hi, its not working.

**Comment by debjeetdebnath** [comment]
I got this problem when I directly downloaded code files from GitHub but it was showing this error, but my colleague told me to use "Git bash here" and use the command to Gitclone it. After doing so it works fine.
