### ISSUE TITLE
 more than 64G  while the List<Partition> partitions = mMassStorageDevices[0]. GetPartitions ();Partitions =null

### ISSUE THREAD

**Issue by saiwaishitou** [magnusja/libaums#139]
When the storage space of the usb flash disk is greater than 64G, the List<Partition> partitions = mMassStorageDevices[0]. GetPartitions ();Partitions =null, what happens?

**Comment by magnusja** [comment]
Can you give some more information?
64GB should not be a problem. Make sure that it is FAT32 though
