### ISSUE TITLE
An extra question that it's slow to decodeStream (bitmap) !

### ISSUE THREAD

**Issue by Gaoxichao** [magnusja/libaums#141]
Hey, guy. I hava a question need your answer. sorry my English is terrible.
    I use this library read file from my Udisk successfully , but I hava a demand that I need show the all of image of Udisk to UI (recycler view).  So I got all the file and screen out the image , and I get the UsbFileInputStream by the image file,then get the bitmap by BitmapFactory.decodeStream( ) to show.
    I don't know why it's so slow when decodeStream , it cost about 8000 ms ( imagefile size is 3.9M) , I replace it from sdcard not udisk ,use the native api , it begin fast (about 800 ms) . I guess it's maybe not code question.
   I don't know it's my code problem or other.

**Comment by magnusja** [comment]
Try wrapping into a buffered input stream.
