### ISSUE TITLE
Seek File not in OutputStream

### ISSUE THREAD

**Issue by adelhoss** [magnusja/libaums#142]
Thank you For Your Great Library
i Use Your Library And success Access To OTG FLASH DISK
But I Want Edit Binary File From OTG 
Exactly I Needed Seek from Binary two byte and modify second byte 
then save back file
i know java have RandomFileAccess with seek method programmer can move in the file 
but after three hour googled can not Convert outputstream to FileAccessRandom 
please help me to seek cursor in file and modify
thx

**Comment by magnusja** [comment]
`UsbFile.write()` is what you are looking for.
