### ISSUE TITLE
partitions's size is zero

### ISSUE THREAD

**Issue by chenxi1991** [magnusja/libaums#145]
UsbMassStorageDevice has an empty partitions

**Comment by magnusja** [comment]
Then no supported file system could be found

**Comment by magnusja** [comment]
Yes it needs to be FAT32

**Comment by chenxi1991** [comment]
@magnusja It turns out that I have the same issue like https://github.com/magnusja/libaums/issues/70. I download your source code and develop branch,and it works for me now. Thanks very much!
