### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for int com.github.mjdev.libaums.a.c()

### ISSUE THREAD

**Issue by viveky259259** [magnusja/libaums#146]
'java.lang.UnsatisfiedLinkError: No implementation found for int com.github.mjdev.libaums.a.c() (tried Java_com_github_mjdev_libaums_a_c and Java_com_github_mjdev_libaums_a_c__) at com.github.mjdev.libaums.a.c(Native Method) at com.github.mjdev.libaums.a.a(Unknown Source) at com.github.mjdev.libaums.d.b.a(Unknown Source) at com.github.mjdev.libaums.a.a.a.a(Unknown Source) at com.github.mjdev.libaums.a.a.a.a(Unknown Source) at com.github.mjdev.libaums.c.a.a(Unknown Source) at com.github.mjdev.libaums.b.a.a.a(Unknown Source) at com.github.mjdev.libaums.b.a.g.a(Unknown Source) at com.github.mjdev.libaums.b.h.read(Unknown Source) at a.a.a.o.b(Unknown Source) at a.a.a.o.a(Unknown Source) at a.a.a.o.a(Unknown Source) at a.a.a.l.a(Unknown Source) at a.a.a.d.run(Unknown Source) at java.lang.Thread.run(Thread.java:818) '

**Comment by magnusja** [comment]
This should not happen. If the c lib fails to load I am not using it: https://github.com/magnusja/libaums/blob/develop/libaums/src/main/java/com/github/mjdev/libaums/ErrNo.java#L16

Can you maybe give me an unobfuscated stack trace?
