### ISSUE TITLE
Copying big file to Sd card too slow

### ISSUE THREAD

**Issue by liaoxsong** [magnusja/libaums#149]
Is there a way to copying file faster to Sd card? I used BufferedInputStream with the length being the chunk size of the flash drive, it takes forever to write a big file ( >=400mb).

**Comment by liaoxsong** [comment]
private int copyFile(UsbFile fromFile, File toFile, int chunksize) {
        if (toFile == null) return 0;//dont make a copy for a folder itself

        BufferedInputStream fosfrom = null;//using bufferedinputstream for performance
        BufferedOutputStream fosto = null;
        try {
            
            fosfrom = new BufferedInputStream(new UsbFileInputStream(fromFile), chunksize);
            fosto = new BufferedOutputStream(new FileOutputStream(toFile), chunksize);
            //UsbFileStreamFactory.createBufferedOutputStream()

            byte buffer[] = new byte[chunksize];
            int c;
            int total = 0;

            while ((c = fosfrom.read(buffer)) > 0) {
                fosto.write(buffer, 0, c);
                total+=c;

                String tcopied = String.format("%.1f", total/1024f/1024f);
                String percent = String.format("%.2f", 100*total/(double) fromFile.getLength());
                publishProgress("Copied:" + tcopied + "mb(" + percent + "%)");
            }
            fosfrom.close();
            fosto.close();
            return 1;
        } catch (Exception ex) {
            LogUtil.e(TAG, "copying error:" + ex.getMessage());
            return 0;
        }
    }

**Comment by magnusja** [comment]
Yes, the library is not really performance optimized.

Did you try different devices (phone and USB pen drive)? Do you get any warnings? Did you test the performance using Total Commander or some other application which supports USB?

**Comment by liaoxsong** [comment]
I tried using an Android 8.0 device and a Android 5.1 device, the 8.0 device is 10 times faster..

**Comment by liaoxsong** [comment]
I just tried Total Commander on my Android 8.0 it takes roughly 3 to 4 times faster than this library.
I think i'm using the default FAT32.

**Comment by magnusja** [comment]
Ok, I see. Unfortunately, I do not have any time to look into this, but you probably want to profile which function takes most of the time.

Do you get any warnings?

**Comment by ljliu1985** [comment]
> Ok, I see. Unfortunately, I do not have any time to look into this, but you probably want to profile which function takes most of the time.
> 
> Do you get any warnings?

If the directory has many files, 4000 or more， It takes too much time to close the input stream

**Comment by liaoxsong** [comment]
actually... I didn't have a lot of files back then, it was just a huge file about 500mb, later I found out it was problem with this old device. I tried other usb apps they were slow too on this old device. The performance on newer android devices are actually good :)
