### ISSUE TITLE
copy files to storage devices,result is succ,but has other messy code files.see more details.

### ISSUE THREAD

**Issue by iLovT** [magnusja/libaums#164]
Hi,I'm from China.Thank you for your repositories.
  Sorry,My English is not good. When I copy file to storage devices,result is succ,but has more 0B and messy code files,and then,not have any error stack. I don't down what happen. Fortunately,the file has been successfully copied.
    see wrong picture,Thanks!

**Comment by iLovT** [comment]
![screenshot_20181122-095214](https://user-images.githubusercontent.com/32090722/49639637-7442f500-fa46-11e8-965f-406285735e6a.png)

**Comment by magnusja** [comment]
Can you try the lastest version `0.6.0`?

**Comment by Gobink6** [comment]
you need writepermission

**Comment by magnusja** [comment]
might be the same problem like #233 and should be fixed in 0.7.3
