### ISSUE TITLE
java.io.IOException: Could not write to device, result == -1 errno 88 Socket operation on non-socket

### ISSUE THREAD

**Issue by MrLiGitHub** [magnusja/libaums#175]
I meet this question that the USB drive is out when Android Device is copying.So it's a good tips to hold the connection.

**Comment by DoubleZhangbo** [comment]
Hi author, i also meet a similar problem. when my app to send "read/write"code (0x28/0x2a), the function(deviceConnection.bulkTransfer) return error code -1 and it shows "IO exception". and then it always fail. but when i send other code (eg. Inquiry0x12), it is normal. look forward you reply.

**Comment by shenqinwei** [comment]
每次断开连接重新插上都要new UsbFile，这样才能解决这个问题。

**Comment by magnusja** [comment]
Please try latest version

**Comment by magnusja** [comment]
closing in favor of #237

**Comment by Depau** [comment]
> errno 88 Socket operation on non-socket

This usually happens when you disconnect the USB drive while it's working. Maybe get a new USB-OTG adapter.

I'd close this.

**Comment by magnusja** [comment]
Oh okay, I did not know that, will close :) thanks!
