### ISSUE TITLE
Unable to read partitions : java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by reemNCQ** [magnusja/libaums#194]
Hello Everyone ... I'm facing a problem with reading from USB Mass storage devices and I hope that I can someone to give me a hint ...
In fact the application can successfully connect to the device but once I'm trying to open and read no partition is detected and I get the following error : 
<img width="673" alt="Screen Shot 2019-07-11 at 2 49 12 PM" src="https://user-images.githubusercontent.com/52405001/61056531-6d6cce00-a3eb-11e9-8e0f-0774cc9973df.png">
So after initializing through `device.init()` no partition is found
PS: the test has been done with usb disk storage that actually work with other file browsing apps ...
I hope I got a fast response and many thanks in advance..

**Comment by magnusja** [comment]
This library currently only supports MBR and FAT32 so make sure that you are using that!

**Comment by reemNCQ** [comment]
Already verified I double checked the storage format.

**Comment by letisoft** [comment]
Hello, 

May be it is related to the same issue I reported on the previous thread?

**Comment by reemNCQ** [comment]
The device should be FAT32 and MBR at the same ... Thank you everyone I'm going close the issue :)
