### ISSUE TITLE
Getting .c extension error 

### ISSUE THREAD

**Issue by Basavaraj1991** [magnusja/libaums#245]
CMake Error at CMakeLists.txt:11 (add_library):
Cannot find source file:
null/libusb/core.c
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
.hxx .in .txx

Getting above error when i try to run the code

**Comment by Depau** [comment]
Hi,
you need to dowload a `libusb-1.0.23` tarball somewhere in your system, then add

```
libusb.dir=/path/to/libusb-1.0.23
```

to `local.properties`.

**Comment by Depau** [comment]
Please beware of the [licensing issues](https://github.com/magnusja/libaums/tree/develop/libusbcommunication) you might incur if you want to include the libusb-based UsbCommunication in a non-open source application

**Comment by Basavaraj1991** [comment]
Hey I've requirement I've copy from android internal storage to USB(pendrive) I'm not getting how to do can you please help me.

**Comment by magnusja** [comment]
Any reason that you are compiling libaums yourself? If you want to use it I would just declare it as a dependency.

This is described in the readme as well as supported in the example application, please consult both of these resources.
