### ISSUE TITLE
UsbMassStorageDevice.init

### ISSUE THREAD

**Issue by cherryzhang-zq** [magnusja/libaums#252]
Hello, when I call "UsbMassStorageDevice.init()",I will get a notification -- USB removed unexpectedly

So,can you help me?

**Comment by cherryzhang-zq** [comment]
Notes: It also can still read and write.
I just don't want USB removed

**Comment by magnusja** [comment]
This is an Android generated notification libaums can nothing do about.

If you use libaums and the USB drive is mounted within Android, Android looses cannot access it anymore and therefore shows this notification. But this is perfectly fine.

**Comment by cherryzhang-zq** [comment]
Thank you! I get it.
But it will make the USB mass storage error. The U disk inserted in the computer is abnormal and needs to be repaired.
You would still care, wouldn't you?

**Comment by magnusja** [comment]
Well this has nothing to do with the notification you are getting I would assume. What does the repair log say? (Please open another issue specifically for that)
