### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by zkjmyy** [magnusja/libaums#265]
My app has a jniLibs folder with xxx.so file inside. If you don't rely on com.github.mjdev:libaums:0.6.0, these libraries can run normally, but if you rely on com.github.mjdev:libaums:0.6.0. Will appear java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader causes my own library to not run normally. The development tool is AndroidStudio. Have you encountered this situation?

**Comment by magnusja** [comment]
No never had this isssue. Seems like that your shared object gets removed in the process of creating the apk. Can you have a look into the apk to confirm this?
