### ISSUE TITLE
SCSI command

### ISSUE THREAD

**Issue by anneyking** [magnusja/libaums#277]
Hello, everyone. Could you tell me how to send SCSI command?? 
Are there any SCSI command documents here?

**Comment by magnusja** [comment]
Have a look here: https://github.com/magnusja/libaums/tree/develop/libaums/src/main/java/com/github/mjdev/libaums/driver
And also my thesis: https://www.in.tum.de/fileadmin/w00bws/os/Lehre/Abschlussarbeiten/Jahnen-thesis.pdf

The thesis has a lot of references with even more exhaustive documentation.
