### ISSUE TITLE
Devices without MBR

### ISSUE THREAD

**Issue by vleitch** [magnusja/libaums#281]
I know this has been reported many times and I notice back in 2017 there was a branch created to resolve this. However the link to this branch returns a 404. 

Is this still available?

Thanks

**Comment by magnusja** [comment]
Should be here yes https://github.com/magnusja/libaums/blob/develop/libaums/src/main/java/com/github/mjdev/libaums/partition/fs/FileSystemPartitionTableCreator.kt

But could be that due to a recent change this is not working anymore?

**Comment by vleitch** [comment]
Thanks for the reply.
It's a FAT12 device - could that be the problem?

**Comment by magnusja** [comment]
Oh yeah FAT12 is not implemented only FAT32
