### ISSUE TITLE
Absolute path

### ISSUE THREAD

**Issue by SanthoshDammu** [magnusja/libaums#282]
### Problem
Unable to find the absolute path of USB mass storage.

### Expected behavior

Absolute path = "/mnt/usb_storage/..."
### Actual behavior
String absPath = currentFs.getRootDirectory().getAbsolutePath();
getting abspath just "/"
Absolute path = "/"

#### Stacktrace of Excpetion

```
(if exists)
```

**Comment by magnusja** [comment]
Hey there,

so for this library the absolute path is indeed `/`. The path with `/mnt/..` is more an Android / Linux style mount path. This is managed by the Linux kernel, which this library is completely independent from.

If your Android device supports mounting usb drives you do not need this library, you can just use the standard ways of accessing files in the Android file system and use `/mnt/...`.
