### ISSUE TITLE
UsbFile::listFiles not returning contents of folder

### ISSUE THREAD

**Issue by Derpalus** [magnusja/libaums#285]
### Problem
When calling `UsbFile::listFiles` on a particular folder on an SD card I get an empty list returned, even though the folder contains a number of subfolders.

### Expected behavior
All files and folders in the folder should be returned

### Actual behavior
No files or folders are returned

### Code where problem occurs
I have tracked the problem to `FatDirectory::listFiles()` -> `FatDirectory::init()` -> `FatDirectory::readEntries()`
In `readEntries()` the expected subfolders just aren't found (some entries are found, but are removed again as the `isDeleted` flag is set on them). I don't know what is happening, could it be some FAT corruption issue? The SD card and its folders are read correctly in Windows and in the normal Android file manager.

Edit: If needed I can provide a 32 GB image of a card where the issue occurs for reproduction.

The more I look at this the more it seems like a FAT issue. For example, moving or renaming the folder does not fix the problem, but copying the subfolders back into the same folder (in Windows) and removing the original ones does work, and calling listFiles on the source folder will then work again. This is probably related to the device that writes the card which is based on some custom version of Android I think. There haven't been any issues reading SD cards from the device using an earlier version of the library, however.

**Comment by magnusja** [comment]
Fixed with v0.9.4
