### ISSUE TITLE
Why  receive ACTION_MEDIA_UNMOUNTED broadcast  Clearly did not pull out the U disk

### ISSUE THREAD

**Issue by zgmd** [magnusja/libaums#291]
#### Stacktrace of Excpetion

```
(if exists)
```

**Comment by zFDT** [comment]
You can try to use UsbManager.ACTION_USB_ACCESSORY_DETACHED and UsbManager.ACTION_USB_ACCESSORY_ATTACHED)

**Comment by zgmd** [comment]
ok,thanks

**Comment by magnusja** [comment]
`ACTION_MEDIA_UNMOUNTED` means that the media was umounted, not removed!

So what it tells you is that your Android OS is capable of mounting USB disks. You can just access files as usual over built in Android tools. If you tell `libaums` now to access the USB disk, then the media is unmounted from Android OS.
