### ISSUE TITLE
about with Folder operation

### ISSUE THREAD

**Issue by AtenzaZoom** [magnusja/libaums#303]
I had some problem，Copy files can be used，but how can i copy the folder？
And how can i decompress the files in the USB flash drive

**Comment by magnusja** [comment]
For copying a folder see example app.

Decompressing is out of scope of this library. But you have raw byte access to files so I dont see a problem using another library for decompressing

**Comment by AtenzaZoom** [comment]
I use a method of UsbFile delete().and then makes an error about errorMessage is file is a directory.so it means can not delete empty directory?

**Comment by magnusja** [comment]
Are you using `java-fs` module? Which file system?
