### ISSUE TITLE
Can't read All file in USB 

### ISSUE THREAD

**Issue by Duckrae** [magnusja/libaums#304]
I'm making a App transfer file from USB to Android Device. It was working good. When i have a 50 video files in USB, this package can read 50 video file and transfer to Android Device. But I checked it yesterday, this package read only 11~14 files in USB. and I don't know why this package not working suddenly. There is no firmware update, no App update and etc.. .Especially , In Android Studio, i check the log , sometime, file name was truncate. I think My video file name is long so i change the video file name as a,b,c,d .... and the package read all file. My video file name is wrong? but it was work when video file name was long. Could anyone give me a advice?

**Comment by magnusja** [comment]
Fixed with new version
