### ISSUE TITLE
没有java版的demo吗，kt看着真难受，

### ISSUE THREAD

**Issue by boylab** [magnusja/libaums#307]
#### Stacktrace of Excpetion

```
(if exists)
```

**Comment by magnusja** [comment]
https://github.com/magnusja/libaums/tree/19c2bec807e7e331151bec8516f3a0933d294454/app/src/main/java/com/github/mjdev/libaums/usbfileman

pre v0.8.0 that is there case, but it is unsupported official language for Android is now Kotlin, Google deprecated Java...

Please use english here as I am not Chinese, I also do not speak any Chinese!

**Comment by boylab** [comment]
thank you for answer me，It doesn't matter what language.
