### ISSUE TITLE
Maven publishing is not working

### ISSUE THREAD

**Issue by lennynilsson** [magnusja/libaums#309]
### Problem
Bintray has been shut down and therefore no artifact will be published.
There inconsistencies in the Maven Central repository which prevents any artifact to be downloaded.
Eather 

### Expected behavior
Pom files and artifacts should be available on Maven Central for new releases

### Actual behavior
No pom file or artifact are available on Maven Central
* This artifact has no POM, but an AAR: [https://repo.maven.apache.org/maven2/com/github/mjdev/storageprovider/0.5.0/](https://repo.maven.apache.org/maven2/com/github/mjdev/storageprovider/0.5.0/)
* This artifact has no AAR, bat a POM: [https://repo.maven.apache.org/maven2/com/github/mjdev/libaums-storageprovider/0.5.0/](https://repo.maven.apache.org/maven2/com/github/mjdev/libaums-storageprovider/0.5.0/)

#### Stacktrace of Excpetion

[https://travis-ci.org/github/magnusja/libaums](https://travis-ci.org/github/magnusja/libaums)
[https://bintray.com/magnusja/maven/libaums/_latestVersion](https://bintray.com/magnusja/maven/libaums/_latestVersion)

### Code where problem occurs

[https://github.com/magnusja/libaums/blob/master/build.gradle](https://github.com/magnusja/libaums/blob/master/build.gradle)

**Comment by lennynilsson** [comment]
Hi @magnusja, I'm sorry to bring you yet another issue. On behalf of my company I would like to thank you for the contributions you've done thought this library.

Let me know if there is anything I can do to help in order to resolve this publishing issue.

**Comment by magnusja** [comment]
See https://github.com/magnusja/libaums/issues/315#issuecomment-930520993
