### ISSUE TITLE
Library release without Jcenter estimated date?

### ISSUE THREAD

**Issue by makserge** [magnusja/libaums#315]
### Problem
Libaums still use deprecated Jcenter repository (https://blog.gradle.org/jcenter-shutdown)

I found that issue already fixed in this comit
https://github.com/magnusja/libaums/commit/c2d45730f7ae4ac6ca07703f4cb70b5bc0673ebc

When you planned to make next release with this commit included?

**Comment by magnusja** [comment]
Sorry, I am currently doing some refactoring to publish to maven central, jcenter is readonly so I cannot push any new versions there.

Currently I am suffering from a covid infection so this might still take some time sorry
