### ISSUE TITLE
Support for Fat Formats (Fat Default)

### ISSUE THREAD

**Issue by dgerchcovich** [magnusja/libaums#321]
Hi,

Awesome library! Is there any chance in allowing for support for Plain Fat Format (non Fat32, but just Fat)?
I have a requirement that users will plug in specific flash storage devices that are less than 500Mb. Fat32 is of course too big for these devices.

Do you know of any other library that supports plain Fat Format? Or is there any plans to support this format in this library.
Thanks

**Comment by magnusja** [comment]
Have you looked at the experimental `java-fs` module?
