### ISSUE TITLE
How can I use PackageManager.getPackageArchiveInfo on USB file

### ISSUE THREAD

**Issue by xulifan** [magnusja/libaums#322]
### Problem
I am developing virus scan application. I need scan the files inside USB drive. With libaums, I can list all the files inside a USB drive. However, to parse an APK file using PackageManager.getPackageArchiveInfo, I need the full path of the file. How can I do this with libaums?

#### Stacktrace of Excpetion

```
(if exists)
```

**Comment by magnusja** [comment]
Not possible as this is a user space lib. You need to parse the apk yourself or see if it offers an API which does not take file path but instead raw bytes.

**Comment by magnusja** [comment]
maybe the storageprovider module can help but I am unsure
