### ISSUE TITLE
close problem

### ISSUE THREAD

**Issue by lawas2008** [magnusja/libaums#328]
### Problem
I have a problem,UsbDevice.close(), App crashed.  error log like this:
![QQ截图20211227154732](https://user-images.githubusercontent.com/10286773/147448499-49753a00-4140-491e-8d06-fd40720c91e0.png)
 My Code like this:
![111](https://user-images.githubusercontent.com/10286773/147448765-6428416b-054e-4465-9b31-1b1b8f5b815a.png)

![2](https://user-images.githubusercontent.com/10286773/147448766-f075ce5f-eb87-4295-85d9-381e1930597f.png)

![33](https://user-images.githubusercontent.com/10286773/147448770-5e358e86-7a36-4b55-abba-ac39f3e16f59.png)

![444](https://user-images.githubusercontent.com/10286773/147448774-9c498223-f00c-456f-be93-e1d9874bfc3d.png)

**Comment by magnusja** [comment]
This happens if you close the USB device twice.

**Comment by lawas2008** [comment]
thank you,I am trying...
