### ISSUE TITLE
libusb init fails on unrooted Android device

### ISSUE THREAD

**Issue by clifforous** [magnusja/libaums#334]
### Problem

When the libusbcommunication (v0.2.2) module initializes the libusb library on an Android device an error is thrown and initialization fails.   I believe this is because by default libusb (tested on v1.0.25) will try to enumerate devices.  The libusb [README](https://github.com/libusb/libusb/blob/master/android/README) for Android suggest disabling enumeration for unrooted android devices.

>    About LIBUSB_OPTION_NO_DEVICE_DISCOVERY:
>
>    The method libusb_set_option(&ctx, LIBUSB_OPTION_NO_DEVICE_DISCOVERY, NULL)
>    does not affect the ctx.
>    It allows initializing libusb on unrooted Android devices by skipping
>    the device enumeration.

### Expected behavior

libusb initialization should succeed on an unrooted Android device

### Actual behavior

libusb initialization fails when trying to enumerate devices

### Code where problem occurs

https://github.com/magnusja/libaums/blob/v0.9.1/libusbcommunication/src/c/usb.c#L12
```
JNIEXPORT jboolean JNICALL
Java_me_jahnen_libaums_libusbcommunication_LibusbCommunication_nativeInit(JNIEnv *env, jobject thiz, jint fd, jlongArray handle) {
    LOG_D(TAG, "init native libusb");
    int ret = libusb_init(NULL);
    if (ret != 0) {
        LOG_E(TAG, "libusb_init returned %d, %s", ret, libusb_strerror(ret));
        return (jboolean) JNI_FALSE;
    }
    ...
```

### Solution

Configure libusb to not enumerate devices during initialization

`libusb_set_option(NULL, LIBUSB_OPTION_NO_DEVICE_DISCOVERY, NULL)`

**Comment by magnusja** [comment]
Hmm is this new? I feel like this always worked on version 1.0.24 and 1.0.23
