### ISSUE TITLE
Putting 200 files in a subdirectory will cause some to be lost

### ISSUE THREAD

**Issue by bcichowlas** [magnusja/libaums#341]
### Problem
If I put about 130-200 files in a subdirectory, some are lost.

### Expected behavior
In my test case, I am only writing files and counting the directory size and I'm not near the capacity of the USB drive, so I would expect all the files to be retained.

### Actual behavior
I wrote a simple example which created a subdirectory and added 200 files, one-by-one at 15-second intervals, counting the files in the subdirectory after adding each one. Using versions 0.8.0 and 0.9.0, after 130 files the total. number of files in the directory went up and down, but ended near 130. For version 0.5.6, libaums worked fine. I've attached abridged logs of the results of my test code.

#### Stacktrace of Excpetion
n/a - No exception occurred.

```
(if exists)
```

### Code where problem occurs
[With0.5.5txt.txt](https://github.com/magnusja/libaums/files/8551461/With0.5.5txt.txt)
[With0.8.0.txt](https://github.com/magnusja/libaums/files/8551462/With0.8.0.txt)
[With0.9.0.txt](https://github.com/magnusja/libaums/files/8551463/With0.9.0.txt)

(later)
I tried this with 0.7.4, which seemed okay. I couldn't find aar's for 0.7.5 and 0.7.6, so I didn't try them. I also found the current new one, 0.9.1 and it still has the problem. So basically, the problem seems to have been introduced between 0.7.4 and 0.8.0 .

Also, I ran tests with my client's program. Combining those results with earlier ones I did, it seems that the maximum number of files that will appear in the subdirectory will be under 140, even if hundreds of files are added.

When I tested with 0.9.1, I was writing about 150 files and then about an additional 230. When I moved the USB to a Windows PC and did a :dir: on the subdirectory, the listing started with . and .. as is usual, I think, but then, about halfway through, there was another . and .. . At the end, it said that the directory contained 4 directories, not 2.

Hope that information helps. I do like using libaums and will stick with 0.7.4 for the time being.

**Comment by magnusja** [comment]
Seems to be same as https://github.com/magnusja/libaums/issues/298
