### ISSUE TITLE
播放U盘上的视频文件

### ISSUE THREAD

**Issue by 2324690091** [magnusja/libaums#344]
我想播放U盘上的视频文件必须得下载到本地才能播放吗？不能直接在当前U盘播放吗？  这个文件的真实路径在哪获取呢

**Comment by hugonnyy** [comment]
hello, do you have solved the problem?

**Comment by zhoubingxing** [comment]
> 我想播放U盘上的视频文件必须得下载到本地才能播放吗？不能直接在当前U盘播放吗？ 这个文件的真实路径在哪获取呢

你好，这个问题请问有解决方案了吗，目前我也是缓存到本地播放，但是大文件相当的慢
