### ISSUE TITLE
UsbFileOutputStream write operation limited to 500 bytes

### ISSUE THREAD

**Issue by yurymelnikov** [magnusja/libaums#351]
Hi,
If I try write to USB drive chunks with size more then 500 bytes, the stored data is corrupted.  But if I divides data to chunks of 500 bytes, so copying file 8Mb from smartphone to USB drive takes more than 2 minutes. 
Why  UsbFileOutputStream is limited to 500 bytes data?

**Comment by magnusja** [comment]
Are you using the example app? The example app is using a bigger buffer size I think.
Never had probelms with that tbh. 

Does the example app work properly for you?
