### ISSUE TITLE
how to read files from ntfs partition of a usb

### ISSUE THREAD

**Issue by weiwsy** [magnusja/libaums#352]
### Problem
NTFS partitions of usb disk can't be read , is there a plan to support it ?

If the usb disk have a ntfs partition and a fat32 partition，  the code below， will returned 1 .
massDevice.getPartitions().size()

### Expected behavior
it should be 2， and can get the partition ：
ntfs = massDevice.getPartitions().get(0)
fat32 = massDevice.getPartitions().get(1)

### Actual behavior
it returned 1, and can't the ntfs partition.

#### Stacktrace of Excpetion

```
(if exists)
```

### Code where problem occurs
![upan](https://user-images.githubusercontent.com/5856839/185831401-d2568b4e-bdaa-4686-b8be-08e1eb167e3e.jpg)

massDevice.getPartitions()

**Comment by magnusja** [comment]
Highly experimental support through java-fs module available.
