### ISSUE TITLE
After created a dir var using root.createDirectory, I lost my other files! 

### ISSUE THREAD

**Issue by Linger50** [magnusja/libaums#353]
### Problem
There are 200 files in my usb device.
![3](https://user-images.githubusercontent.com/7641437/186057207-cfeb739f-16ce-47e4-8612-c71beaab8c31.png)

after call method root.createDirectory("aaa");

I lost my other files.
![4](https://user-images.githubusercontent.com/7641437/186057228-65a732d0-dcce-4019-a1b2-0d5b0a32868d.png)

### Expected behavior
the dir Created, and other files exist, and can be shown

### Actual behavior
the dir Created, other files deleted, and only show about 30 files

**Comment by magnusja** [comment]
Not sure, maybe the chinese symbols are not supported? 

Is it FAT32?

**Comment by magnusja** [comment]
Probably related to #298
