### ISSUE TITLE
Unsupported fs on partition

### ISSUE THREAD

**Issue by walt-zhong** [magnusja/libaums#354]
### Problem
Current lib only support FAT32,But Now ,the format of most USB is extFat.unable to get Partition instance，so can not read the USB 

### Expected behavior
USB of any format can be used

### Actual behavior
Only Fat32 format can be used  

#### Stacktrace of Excpetion

```
(if exists)
```

**Comment by magnusja** [comment]
Highly experimental support available with java-fs module. Please read the manual before submitting an issue!
