### ISSUE TITLE
Index out of bound

### ISSUE THREAD

**Issue by sachinrana028** [magnusja/libaums#362]
I am getting index out of bound exception. Currently, my usb drive has no partitions. So, is there any other way to get filesystem of a device?
val currentFs = device.partitions[0].fileSystem

**Comment by magnusja** [comment]
What file system is the drive formatted with you are trying to access?

**Comment by magnusja** [comment]
Are you using the java fs module?

**Comment by sachinrana028** [comment]
I am using Kotlin module.

**Comment by sachinrana028** [comment]
I tried with java fs module and I am getting same index out of bound exception.

**Comment by magnusja** [comment]
Then you should check that you are using MBR instead of GPT
