### ISSUE TITLE
ScsiBlockDevice fix

### ISSUE THREAD

**Issue by GrieVeR-13** [magnusja/libaums#363]
### Problem
`me.jahnen.libaums.core.driver.scsi.ScsiBlockDevice`
contains error in line (initialized in the constructor and always equal to 0):
`override val blocks: Long = lastBlockAddress.toLong()`
Need replace with

`override val blocks: Long 
   get() = lastBlockAddress.toLong()`

**Comment by magnusja** [comment]
Thanks!
