### ISSUE TITLE
device.getPartitions() is Empty

### ISSUE THREAD

**Issue by bqrfvatj** [magnusja/libaums#366]
### Problem
            device.init();
            Partition partition = device.getPartitions().get(0);
            System.out.println(partition)   // result =  null ?????????

             Why? How to solve it?
#### Stacktrace of Excpetion

```
(if exists)
```

**Comment by anmolthedeveloper** [comment]
Same

**Comment by magnusja** [comment]
Then you are either using an unsupported partition table (e.g. GPT instead of MBR) or an unsupported file system. Only FAT32 is supported.

**Comment by magnusja** [comment]
GPT now supported!
