### ISSUE TITLE
Folder names are displayed in all caps.

### ISSUE THREAD

**Issue by aravind14feb** [magnusja/libaums#40]
If all the characters in a folder name are lower case letters, then the libaums library is displaying them in upper case characters.

![untitled](https://cloud.githubusercontent.com/assets/5258874/20716086/489d2228-b677-11e6-8a28-435ba7d3198d.png)

![screenshot_2016-11-29-20-18-29](https://cloud.githubusercontent.com/assets/5258874/20715944/bf4c4eb8-b676-11e6-9022-69978a0f2145.png)

on Running with Storage Access Framework

![screenshot_2016-11-29-20-18-45](https://cloud.githubusercontent.com/assets/5258874/20715963/cc746f1c-b676-11e6-93f8-e48566ba8bda.png)

Problem is consistent and easily reproducible.

**Comment by magnusja** [comment]
Hey, so I tried that.
Unfortunately when I am creating a folder with all caps or with all lower case it still only creates a usual directory entry for both cases. As far as I know the FAT32 spec for the latter case there should be an lfn entry, but apparently, it is not created or there is a bug in my code somewhere.

So if you have any idea this is highly appreciated.

**Comment by magnusja** [comment]
Found it: https://en.wikipedia.org/wiki/8.3_filename#Compatibility
