### ISSUE TITLE
Small fix in example app

### ISSUE THREAD

**Issue by AdiSegev** [magnusja/libaums#55]
Your library really saved my day in order to copy files to USB storage.

I think there's some bug in your MainActivity:

in line 750: should check entry.getName().lastIndexOf("."), in case there's no file extension.
I think it can be fixed like this:
int index = entry.getName().lastIndexOf(".")>0?entry.getName().lastIndexOf("."):entry.getName().length();

**Comment by magnusja** [comment]
Thanks
