### ISSUE TITLE
Sorting usb file type(video, photo, audio, etc...)

### ISSUE THREAD

**Issue by wbjaa** [magnusja/libaums#58]
Hello,
I am developing an app to access USB,
Do u have sorting files type function like (MediaStore.Audio.Media.DATA)?
sorry for my bad English,
thank you for your develope.

**Comment by magnusja** [comment]
Hey,

no there is nothing like that, and this is also way beyond the scope of this library.

I suggest that you use `UsbFile#listFiles()` to look for files you are interested in. You can, for example, filter for certain file extensions (mp3, mp4, ...).

**Comment by wbjaa** [comment]
thanks for your reply.
I will try it. appreciate it.

**Comment by magnusja** [comment]
You are welcome!
