### ISSUE TITLE
no device

### ISSUE THREAD

**Issue by duwurensheng010** [magnusja/libaums#63]
Why i can not get my device?

**Comment by duwurensheng010** [comment]
I connect with Digital camera。

**Comment by magnusja** [comment]
Is there no partition or no device at all?

Can you maybe install the UsbDevice Info App and post some screenshots with information? Especially interesting are device class and the endpoints.

https://play.google.com/store/apps/details?id=aws.apps.usbDeviceEnumerator&hl=en

**Comment by duwurensheng010** [comment]
https://play.google.com/store/apps/details?id=aws.apps.usbDeviceEnumerator&hl=en
I can get device info with this app，Device path is not the file path？

**Comment by magnusja** [comment]
So what is the device info? Can you post some screenshots, please?
Device path something low level, which is not of interest.

**Comment by duwurensheng010** [comment]
![f0d09c31-c695-4cb8-84f5-d14aeaf73bd7](https://cloud.githubusercontent.com/assets/7730269/23243391/97167f5a-f9b9-11e6-8c8e-3825918bfa7c.png)

**Comment by magnusja** [comment]
So the device class "Still Image Device (0x6)" is not supported in libaums. libaums only supports USB Mass Storage devices (https://en.wikipedia.org/wiki/USB_mass_storage_device_class).
If you cannot find a USB interface with that class, your camera does not support simulating such a device. What you can try then is using an SD card reader instead.

**Comment by duwurensheng010** [comment]
Oh, I know, thank you very much

**Comment by magnusja** [comment]
You are welcome!
