### ISSUE TITLE
Subtle bug in SCSI command length

### ISSUE THREAD

**Issue by hooby3dfx** [magnusja/libaums#64]
First of all - awesome project!

I wanted to point out something which seems to be an accident.
In ScsiRead10 and all other command classes, the LENGTH field is declared in hex:
`private static final byte LENGTH = 0x10;`
This command should be length 10 as per spec - but in this code will actually be 16 (decimal)!

Luckily, these commands still seem to work as is - I noticed this when creating other SCSI commands by copy pasting and blindly putting other lengths in hex.

**Comment by magnusja** [comment]
Hey there,

thanks for reporting. Good catch!
