### ISSUE TITLE
Is it possible to connect with camera device?

### ISSUE THREAD

**Issue by lesniakania** [magnusja/libaums#69]
I try to use your library (very nice to use API by the way!) to connect to Nikon camera.
I've already managed to do this using [MTP protocol](https://developer.android.com/reference/android/mtp/MtpDevice.html), without your library before.
But I need to send data to the device too (using MTP protocol it's possible from API level 24...).

I would like to use your library, but I don't see any devices listed using `getMassStorageDevices`, when I connect my Nikon, while I see it and can copy files from it using pure MTP (so I guess permissions should be fine).

**Comment by magnusja** [comment]
Hey there,

thank you!
So this library only focuses on USB mass storage devices and therefor unfortunately does not support the MTP or PTP protocol.

What you can try from here:
1. If you do not need to connect your camera directly, you can use the SD card from your camera and a USB SD card reader instead.
2. Use a different library. What I found with a quick search:
- https://github.com/crazymaik/remoteyourcam-usb
- https://github.com/terencehonles/Android_USB_PTP_Lib
I haven't tested any of them so I can't recommend, but the first one looks quite promising I think.
