### ISSUE TITLE
can not read Fat 16 usb

### ISSUE THREAD

**Issue by yoll522** [magnusja/libaums#72]
this library is petty perfect

but I can not read Fat 16 usb

What am I doing wrong?

or this library can not read Fat 16 ?

(sorry for my poor English)

**Comment by magnusja** [comment]
No libaums does not support FAT16.

What you can try: There is an experimental version in master, which uses the jnode operating system implementations for file systems. You need to check out the master branch and add this somewhere before using any other method of libaums:

```
FileSystemFactory.registerFileSystem(new JavaFsFileSystemCreator());
```

After that you should be able to read FAT16 and many other file systems. But support is currently highly experimental and you may experience performance decreases.
