### ISSUE TITLE
Support for volumes without MBR?

### ISSUE THREAD

**Issue by martinlie** [magnusja/libaums#74]
I am interested in getting out of the Android Storage Access Framework by using a library like this - but my MSD device is created without MBR, as a "super floppy disk" (SFD) (filesystem created on the fly on the embedded side using the FF library).

Are there plans to support this method alongside MBR, or how much work is needed to make such support do you think?

**Comment by magnusja** [comment]
Hey there,

so I have currently no plans supporting this. If you would like to implement this, I would appreciate a PR. 

Have a look at this package: https://github.com/magnusja/libaums/tree/develop/libaums/src/main/java/com/github/mjdev/libaums/partition

You need to create a new class for SFD which implements PartitionTable and then in the factory create either a MBR or a SFD instance. The MBR for instance returns null if it cannot find a valid MBR partition table.
