### ISSUE TITLE
When I finished, I had a lot of 0kb files

### ISSUE THREAD

**Issue by dllsndy** [magnusja/libaums#75]
I downloaded about more than and 100 small files, divided into several folders.
After the completion of the download more than a fixed number of 0kb files, and some will be deleted file name is invalid or too long. And I clone your project, found that there will be a problem, how to solve this problem?

**Comment by dllsndy** [comment]
copy .not download

**Comment by dllsndy** [comment]
/0003 has entries after end of directory. '/0003' is a directory.How should I solve it?

**Comment by magnusja** [comment]
Can you show some code?

**Comment by dllsndy** [comment]
this is write(); 
new Thread(new Runnable() {
                @Override
                public void run() { 
   UsbFile root = massDevice.getPartitions().get(0).getFileSystem().getRootDirectory();
                     for (File file : files) { if (file.isDirectory()) {
                                UsbFile orderDirectory = root.search(file.getName());
                                if (orderDirectory== null) {
                                  orderDirectory = root.createDirectory(file.getName());
                                }
FileManager.copyAllUsbFile(file.getPath(), orderDirectory, massDevice.getPartitions().get(0).getFileSystem());
 }).start();

and copyAllUsbFile(String,String,FS);

{
        File dir = new File(srcFileStr);
        if (!dir.exists()) {
            return false;
        }
        File[] files = dir.listFiles();
        byte[] buffer = new byte[currentFs.getChunkSize()];
        for (File file : files) {
            if (file.isDirectory()) {
                continue;
            } else if (file.isFile()) {
                Uri uri;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    uri = FileProvider.getUriForFile(MyApp.getMyApplication(),
                            MyApp.getMyApplication().getApplicationContext().getPackageName() + ".fileprovider",
                            file);
                } else {
                    uri = Uri.fromFile(file);
                }
                InputStream input =MyApp.getMyApplication().getContentResolver().openInputStream(uri);
//                FileInputStream input = new FileInputStream(file);
                FatFile searchFile = (FatFile) root.search(file.getName());
                if (searchFile != null) {
                    L.e("delete" + searchFile.getName());
                    searchFile.delete();
                }
                 searchFile = (FatFile) root.createFile(file.getName());
                searchFile.setLength(file.length());
                L.i("msg createFile=", searchFile.getName());
              BufferedOutputStream out = UsbFileStreamFactory.createBufferedOutputStream(searchFile, currentFs);
 //                 UsbFileOutputStream out=new UsbFileOutputStream(searchFile);
                int len = 0;
                //TODO
                L.e("write" + searchFile.getName());
                while ((len = (input.read(buffer))) != -1) { 
                    out.write(buffer,0, len);
                }
                out.flush();
                input.close();
                out.close(); 
            }
        }
    }

**Comment by dllsndy** [comment]
like this.
![1494579644 1](https://cloud.githubusercontent.com/assets/19181820/25991091/b4a4ce7e-3734-11e7-8fd9-9ddfe5ea8249.jpg)

**Comment by dllsndy** [comment]
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 155 continues with cluster 156 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 156 continues with cluster 157 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 157 continues with cluster 158 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 158 continues with cluster 159 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 159 continues with cluster 160 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 160 continues with cluster 161 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 161 continues with cluster 162 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 162 continues with cluster 163 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 163 continues with cluster 164 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 164 continues with cluster 165 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 165 continues with cluster 166 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 166 continues with cluster 167 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 167 continues with cluster 168 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 168 continues with cluster 169 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 169 continues with cluster 170 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 170 continues with cluster 171 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 171 continues with cluster 172 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 172 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 173 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 174 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 175 continues with cluster 176 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 176 continues with cluster 177 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 177 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 178 continues with cluster 179 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 179 continues with cluster 180 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 180 continues with cluster 181 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 181 continues with cluster 182 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 182 continues with cluster 183 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 183 continues with cluster 184 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 184 continues with cluster 185 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 185 continues with cluster 186 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 186 continues with cluster 187 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 187 continues with cluster 188 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 188 continues with cluster 189 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 189 continues with cluster 190 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 190 continues with cluster 191 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 191 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 192 continues with cluster 193 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.445 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.445 432-442/? I/fsck_msdos: Cluster 193 continues with cluster 194 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 194 continues with cluster 195 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 195 continues with cluster 196 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 196 continues with cluster 197 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 197 continues with cluster 198 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 198 continues with cluster 199 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 199 continues with cluster 200 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 200 continues with cluster 201 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 201 continues with cluster 202 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 202 continues with cluster 203 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 203 continues with cluster 204 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 204 continues with cluster 205 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 205 continues with cluster 206 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 206 continues with cluster 207 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 207 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 208 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 209 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 210 continues with cluster 211 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 211 continues with cluster 212 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 212 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 213 continues with cluster 214 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 214 continues with cluster 215 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 215 continues with cluster 216 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 216 continues with cluster 217 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 217 continues with cluster 218 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 218 continues with cluster 219 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 219 continues with cluster 220 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 220 continues with cluster 221 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 221 continues with cluster 222 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 222 continues with cluster 223 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 223 continues with cluster 224 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 224 continues with cluster 225 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 225 continues with cluster 226 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 226 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 227 continues with cluster 228 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 228 continues with cluster 229 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 229 continues with cluster 230 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 230 continues with cluster 231 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 231 continues with cluster 232 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 232 continues with cluster 233 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 233 continues with cluster 234 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 234 continues with cluster 235 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 235 continues with cluster 236 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 236 continues with cluster 237 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 237 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 238 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 239 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 240 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 241 continues with cluster 242 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 242 continues with cluster 243 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 243 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 244 continues with cluster 245 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 245 continues with cluster 246 in FAT 0, but is marked free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 246 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 247 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED
05-15 10:51:58.446 432-442/? I/fsck_msdos: Cluster 248 is marked as EOF in FAT 0, free in FAT 1
05-15 10:51:58.446 432-442/? I/fsck_msdos: FIXED

**Comment by magnusja** [comment]
Hey there,

so I guess you have the same problem with junk files like #33 and #78. Have a look at #78, I commented something you can try for me.

**Comment by magnusja** [comment]
Can you try current develop branch for me, please?

**Comment by dllsndy** [comment]
ok, I will try it.

**Comment by dllsndy** [comment]
This new example doesn't run into problems.
And there is no problem with my project importing ‘javafs’ and ‘libaums’.
I'm using API 25.

**Comment by magnusja** [comment]
So problem solved,  I assume?

**Comment by dllsndy** [comment]
Yes, thank you for helping me solve this problem.
