### ISSUE TITLE
How to directly read the files on the USB flash drive ?How to get to the path under the USB file?

### ISSUE THREAD

**Issue by liminwu0626** [magnusja/libaums#80]
I encountered the following questions,
![image](https://cloud.githubusercontent.com/assets/11213395/26824439/ff5c1af4-4ae3-11e7-9fad-ca00bd34eda3.png)

**Comment by magnusja** [comment]
This seems to be an error from android itself. https://android.googlesource.com/platform/libcore/+/jb-mr2-release/luni/src/main/java/libcore/io/IoBridge.java#388

Are you even using my library?

**Comment by liminwu0626** [comment]
Yes ,do you mean that I can not get the path directly to the USB drive?

**Comment by magnusja** [comment]
I mean it does not look that your code is calling anything related to my library. all my package names include 'libaums', there is no single libaums in you stacktrace!

It seems you are using the standard Android API. If you show some code I can give you some more input.

**Comment by liminwu0626** [comment]
Oh,sorry,did not understand what you mean...Really thank you four your time... 
You see the following is the function call stack.
![image](https://user-images.githubusercontent.com/11213395/26857360-9c8f4ddc-4b5c-11e7-9dec-c4d6b2d65d76.png)
![image](https://user-images.githubusercontent.com/11213395/26857434-1279f9d4-4b5d-11e7-8169-5f9bc62fd563.png)
![image](https://user-images.githubusercontent.com/11213395/26857421-0023005a-4b5d-11e7-8c44-594d86830d3e.png)

**Comment by magnusja** [comment]
Okay, so this does not work. The standard Java `File` API and libaums are not compatible. So a Java `File` object cannot find something on the USB drive using libaums with a file path or similar.

Instead, you should use the `UsbFileInputStream` like so:
```
workbook = new HSSFWorkbook(new UsbFileInputStream(usbFile));
// or buffered (may increase performance)
workbook = new HSSFWorkbook(UsbFileStreamFactory.createBufferedOutputStream(usbFile, currentFs))
// if you don't have the current fs this shpuld be fine as well
workbook = new HSSFWorkbook(new BufferedInputStream(new UsbFileInputStream(file)))

```

Next time, please read the documentation more carefully. It is explained how to use Input/OutputStreams.

**Comment by liminwu0626** [comment]
Okay,Thank you so much...

**Comment by magnusja** [comment]
You are welcome, I hope it works now!
