### ISSUE TITLE
hi，need help

### ISSUE THREAD

**Issue by fly7632785** [magnusja/libaums#81]
hello,
I want to know how / why  the device.getPartitions() is empty ?
When I  execute device.getPartitions().get(0).getFileSystem();
There is a exception:
`java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)`
It means partitions are empty.
What's the situation happened?
And  the Usb equipment is MS-DOS (FAT16) ，is That wrong？

**Comment by magnusja** [comment]
Hey there,
please refer to this answer: https://github.com/magnusja/libaums/issues/72#issuecomment-296774149
