### ISSUE TITLE
Investigate on SD card issues

### ISSUE THREAD

**Issue by magnusja** [magnusja/libaums#86]
@fly7632785 please let us continue here.

Prior discussion: https://github.com/magnusja/libaums/issues/70#issuecomment-311617027

**Comment by magnusja** [comment]
@fly7632785 so you are showing screenshots with a device of capacity around 32gb and the diskutil list command shows 8gb of capacity. How is that?

I tested with my SD card reader and it did not work at all. It does not even read from the device, but I do not really know why. I emailed the developers of Nexus Media Importer, maybe they have some hints.

**Comment by fly7632785** [comment]
I don't know why it is 8g. May the information is not whole. But the most important is the sd card of the USB equipment doesn't have a MBR partition. I will try to format it or re-partition it. I am not sure it will work. 
I will go to bed now, cause it is deep night.
Hope you have a new process and development, good night

**Comment by magnusja** [comment]
So if there is no MBR then usually it should log 'not a valid mbr partition table' and it does not even try to read partitions from it.

**Comment by fly7632785** [comment]
yes, so we need test. But there are two app which can read directly. I don't know what tech they use.

**Comment by magnusja** [comment]
Which is the other one?
I tried Total Commander with the USB Plugin with my card reader and it does not work.

**Comment by fly7632785** [comment]
If It's not like 'not a valid mar partition' you said. Its  get(offset) of every 16 byte is  just always 0, so always continue to the end.
We compare it to the other USB storage which works, figure it out that it seems it doesn't have a MBR.
If it definitely has a MBR. What cause the partitionType is always 0 and not any one of the PartitionType Arrays

**Comment by fly7632785** [comment]
The other one I meant is a normal USB mass storage, not the USB equipment with a SD card.

**Comment by fly7632785** [comment]
The other apps which can read  are here(https://play.google.com/store/apps/details?id=com.estrongs.android.pop&hl=ja   ;   https://play.google.com/store/apps/details?id=com.homeysoft.nexususb.importer&hl=ja)

**Comment by magnusja** [comment]
0 usually means empty partition table, see here: https://en.wikipedia.org/wiki/Partition_type

Are you sure that it is always 0? Maybe it is an extended partition, that is not supported at the moment as well.

**Comment by fly7632785** [comment]
Yes, what I said is wrong. What I really mean is there is no partition instead of no MBR. 
Yes we debug and it is always 0 four times

**Comment by magnusja** [comment]
Can you create an image for me like here: https://www.cyberciti.biz/faq/how-to-create-disk-image-on-mac-os-x-with-dd-command/

Then please upload and sent it to me. Then I can anaylze it. You might want to limit the size to a couple of 100 of MBs, I do not need the whole 8 or 32gb image.

**Comment by fly7632785** [comment]
By the way, you are in Germany. It is about 3 am? Don't you sleep?

**Comment by magnusja** [comment]
You can also use the disk utility app of OSX no need to use the command line.

I am currently in the US, it is 6pm here :P

**Comment by fly7632785** [comment]
http://jafir-my-love.oss-cn-shanghai.aliyuncs.com/usb.img        
Is this ?
I create it by dd 
If it's useless.
I will try the method of the web

**Comment by magnusja** [comment]
It is only 10 bytes, so literally nothing in there.

**Comment by fly7632785** [comment]
OK I'll try, please hold on.
I am on the way to my company

**Comment by fly7632785** [comment]
http://jafir-my-love.oss-cn-shanghai.aliyuncs.com/backup.my.sdcard.img.dd        about 98M

**Comment by magnusja** [comment]
thanks, I will have a look asap!

**Comment by fly7632785** [comment]
ok

**Comment by fly7632785** [comment]
maybe the USB equipment is GPT not MBR
The 8 GB card is a test card(never mind)
![72d9a794-697c-4323-bf23-61d23636ed22 1](https://user-images.githubusercontent.com/10276266/27718884-78f93eb4-5d81-11e7-9347-ee17dcfd297a.png)

**Comment by magnusja** [comment]
Yes it seems like it is. Try reformatting with MBR.

**Comment by fly7632785** [comment]
yes, I am trying to do that

**Comment by fly7632785** [comment]
May I have your email ?

**Comment by magnusja** [comment]
Sure, it is mjahnen <at> stanford.edu

**Comment by fly7632785** [comment]
mjahnen@stanford.edu  ?

**Comment by magnusja** [comment]
Yes, I just wrote it like that so no one can scrape the email and send me spam.

**Comment by fly7632785** [comment]
ok    roger

**Comment by fly7632785** [comment]
Hi, magnusja. 
if it's GPT, should the framework have a log notice?

**Comment by magnusja** [comment]
According to Wikipedia there is a protective MBR for devices without GPT support. (https://en.wikipedia.org/wiki/GUID_Partition_Table#Protective_MBR_.28LBA_0.29)

That is why libaums recognizes an MBR. I analyzed the file and in fact, there are the magic numbers for an MBR the rest of the file are mostly zeros. So please reformat with MBR and FAT32 then you are good to go.

**Comment by fly7632785** [comment]
I'm sorry to tell you the message.
When I convert it to MBR from GPT.
It still doesn't work....

**Comment by fly7632785** [comment]
the result of debug is still same.

**Comment by fly7632785** [comment]
![7fa1afdf-56d5-485c-9bff-9dcf6d52460d 1](https://user-images.githubusercontent.com/10276266/27720295-625a194e-5d8b-11e7-807e-0f95988a2d60.png)
this is screenshot

`bin-no-MBP:Volumes bingao$  hexdump -C -s 446 -n 64 NO\ NAME/
000001be  ff ff 54 52 41 53 48 45  7e 31 20 20 20 12 00 9b  |..TRASHE~1   ...|
000001ce  af 55 da 4a da 4a 00 00  af 55 da 4a bd 00 00 00  |.U.J.J...U.J....|
000001de  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001fe
`
this is MBR code

But It seems it is wrong.
The fifth byte each 16 is not 0.  But the result of debug is always 0.
Why is that?

**Comment by magnusja** [comment]
This looks like you are already into the file system.
Are you sure you formatted with MBR, maybe the file system starts now directly?

**Comment by fly7632785** [comment]
This is  a info from Hard Disk Manager about the USB equipment.
It shows it is MBR and FAT32.
I didn't format it (what I formatted was the test equipment before), it's just MBR
Is the command code right ?

**Comment by magnusja** [comment]
You need to hexdump on the low-level device like /dev/diskX. I don't know what NO\ NAME is in your hexdump call, but it seems to be the directory of the device?

**Comment by fly7632785** [comment]
yes, your command code is right

**Comment by fly7632785** [comment]
`
bin-no-MBP:Volumes bingao$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *251.0 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage Macintosh HD            250.1 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3

/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                  Apple_HFS Macintosh HD           +249.8 GB   disk1
                                 Logical Volume on disk0s2
                                 8ABB2546-043F-4E17-A20A-8EECAB36BE00
                                 Unlocked Encrypted

/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            NO NAME                *31.9 GB    disk2

`

`
bin-no-MBP:Volumes bingao$ sudo hexdump -C -s 446 -n 64 /dev/disk2
000001be  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001fe
`

**Comment by magnusja** [comment]
try hexdump -C  -n 512 and please make sure the formatting does not get lost.

**Comment by fly7632785** [comment]
bin-no-MBP:Volumes bingao$ sudo hexdump -C -n 512 /dev/disk2
Password:
00000000  eb 00 90 20 20 20 20 20  20 20 20 00 02 40 92 04  |...        ..@..|
00000010  02 00 00 00 00 f8 00 00  3f 00 ff 00 00 20 00 00  |........?.... ..|
00000020  00 04 b7 03 b7 1d 00 00  00 00 00 00 02 00 00 00  |................|
00000030  01 00 06 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  80 00 29 31 63 31 62 4e  4f 20 4e 41 4d 45 20 20  |..)1c1bNO NAME  |
00000050  20 20 46 41 54 33 32 20  20 20 00 00 00 00 00 00  |  FAT32   ......|
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
00000200

**Comment by magnusja** [comment]
I wonder why it says FAT32, if I dump an MBR from a USB flash drive it is all 0s besides the last two bytes and the actual entries.

Can you try this:  `sudo dd if=/dev/disk2 of=/tmp/mbrsda.bak bs=512 count=1` and send the me file

**Comment by fly7632785** [comment]
http://jafir-my-love.oss-cn-shanghai.aliyuncs.com/mbrsda.bak

**Comment by fly7632785** [comment]
NO NAME maybe its name.

**Comment by magnusja** [comment]
Okay, it is exactly the same and the partition type information is all zeros.
So there is something wrong. Either you still have an MBR or there is no boot sector at all??

Can you send some screenshots from the built in macOS disk utility tool, please?

**Comment by fly7632785** [comment]
maybe  the sd card of the usb equipment doesn't have a mbr sector   known by  some books.

**Comment by fly7632785** [comment]
for save space of storage

**Comment by fly7632785** [comment]
![cb53c29e-6f73-4e5b-be9a-160a200aaf63](https://user-images.githubusercontent.com/10276266/27758986-b03b854c-5e55-11e7-944b-159a6eaf38ab.png)

https://stackoverflow.com/questions/38004064/is-it-possible-that-small-sd-cards-are-formatted-without-an-mbr

![fcad1de2-6334-4b85-9594-9f8de07268d0](https://user-images.githubusercontent.com/10276266/27758990-c04fc808-5e55-11e7-899e-8ec40331cac5.png)

**Comment by magnusja** [comment]
Could certainly be. So please reformat with MBR then.

**Comment by fly7632785** [comment]
So, do you know any way to format the scared with MBR?

**Comment by magnusja** [comment]
![screen shot 2017-06-30 at 23 36 39](https://user-images.githubusercontent.com/1659457/27759744-00ac8918-5ded-11e7-8123-1b129b99e332.png)

**Comment by fly7632785** [comment]
![11f9040e-2b14-441d-aece-d2b1c1a32537](https://user-images.githubusercontent.com/10276266/27766951-11ff2aca-5f16-11e7-889e-a2a8832b4628.png)
it's not  Generic STORAGE DEVICE Media which has a function to choose a partition and format, instead of a NO NAME which just has choose Format, no Scheme.

what does that mean ?

**Comment by magnusja** [comment]
Hmm I don't know. What does the thing above the "NO NAME" mean?

**Comment by fly7632785** [comment]
Thank you, it works now.
I have sent the e-mail to you.

**Comment by fly7632785** [comment]
![08074906-fd21-47f2-bb67-fe081f1a79d9 1](https://user-images.githubusercontent.com/10276266/27777998-4fec85ce-5fea-11e7-8adf-c68d8938c871.png)
erase it and reformat it to support MBR and FAT32,
it's OK

**Comment by magnusja** [comment]
Nice, glad you could figure it out!
If you need something else, don't hesitate to ask!

**Comment by fly7632785** [comment]
Hi, @magnusja 
I come again.
What I want to ask is that if there is any way to read data from SDCard without MBR.
Many equipments of the customer are not supported by MBR.

**Comment by magnusja** [comment]
Hey @fly7632785 

I am not sure when I will be able to look into this. The biggest problem is, how can we distinguish between MBR and not MBR/FAT32, if FAT32 looks like MBR? 
If you would like to work on this, I'd be happy to take an PR!

**Comment by fly7632785** [comment]
Yes, What I want to do is investigating whether we can format the SDcard by Android System.
But maybe it need Root or System permission.

**Comment by magnusja** [comment]
Probably not possible without user interaction. In addition, to do that over the Android system, the user needs to plug the SD card into the phone directly (if the device does not support mounting USB drives natively). 
In theory, you could add this functionality to libaums, but then you could also just add support for drives without MBR.

**Comment by magnusja** [comment]
Have a look at this branch: https://github.com/magnusja/libaums/tree/feature/device-without-mbr

I implemented acess for devices without mbr.

**Comment by fly7632785** [comment]
Yes, that's amazing.
I am searching a way to access without MBR
Cause, there's another app which can read without MBR
So In theory, it's practicable

**Comment by magnusja** [comment]
Yeah just try it, for me, it works.

**Comment by fly7632785** [comment]
And magnusja, there are few questions for you.
Could you give me the answers?
1、the logicAddress of the file in the SD card is serial ？
2、though I am learning something about the filesystem from the Libaums, I still have many questions about the fileSystem that how to create the Filesystem tree and read files. I can't find something useful in the domestic web, So could you give me something to learn?
Thanks much

**Comment by magnusja** [comment]
1. What exactly do you mean?
2. There are many file systems out there, which one are you interested in? libaums implements FAT32, which is partly described in my thesis: https://www.os.in.tum.de/fileadmin/w00bdp/www/Lehre/Abschlussarbeiten/Jahnen-thesis.pdf

**Comment by fly7632785** [comment]
hi,magnusja
now I'm using libaums:0.5.5 
but what I see is not fit with the code of the develop_without_mbr
is the code of gradle compile  pointed to master branch?

![09563392-10a6-4d02-bbac-a21d69466a9c](https://user-images.githubusercontent.com/10276266/28815268-5cc276fa-76d3-11e7-913e-8e84ccdb3dd1.png)
![8ec00be9-c49d-4d69-8659-c2357a7b6fa9](https://user-images.githubusercontent.com/10276266/28815289-72356128-76d3-11e7-87b5-2e3b8b67d303.png)

**Comment by fly7632785** [comment]
After I saw your travis-ci
I saw your develop_without_mbr didn't merge with master.
So how can I user that ?
Download? Then add to project manually?

**Comment by magnusja** [comment]
Yes please download the code of the branch and add the src/ folder of libaums directly to your project and remove the gradle dependency.

I will release a new version later, I still have some stuff on my TODO list. Especially tests.

**Comment by fly7632785** [comment]
yes. I have downloaded it and makeJar. Then add it to my project. I will test it today 😁

**Comment by fly7632785** [comment]
now, I dump the 512 of the sdcard of devices by two ways.
First One is  dumping the sdcard in the CardReader device
Another one is dumping the sdcard int the Custom's device

They are different!

![default](https://user-images.githubusercontent.com/10276266/28855233-4c431032-776e-11e7-99e2-76e4302cb39e.png)
the up is by CardReader
the down is by Custom's device 

I can read files from the first way, but can't read by the second way

I doubt there is a transform in the custom's device, leading the 512 code of the SDcard  changed
The custom's device shows Linux File storage gadget 

I am still testing and researching.
Any pointed thing you figure out?

**Comment by magnusja** [comment]
First is probably MBR, second FAT32.

Are you sure you downloaded the correct branch?

**Comment by fly7632785** [comment]
yes, this time I got right branch
but
![c5ce14a2-af51-4669-86be-0bd59f7d7757](https://user-images.githubusercontent.com/10276266/28857567-0c939cc2-777d-11e7-866b-e360f8b4f49b.png)

**Comment by magnusja** [comment]
Hmm strange. It is still creating an MBR.
Can you step into createPartitionTable()?
