### ISSUE TITLE
gradle build fail

### ISSUE THREAD

**Issue by SvenSv** [magnusja/libaums#89]
Hi.
If I include
compile 'com.github.magnusja:libaums:libaums-v0.5.5@aar' 
in my gradle dependencies, I get the message
"Could not find libaums.aar".
When I leave the @aar out: 
compile 'com.github.magnusja:libaums:libaums-v0.5.5'
I get the message 
"Module depends on one or more Android Libraries but is a jar".

Am I doing something wrong?

**Comment by magnusja** [comment]
Hey there,

the following should work
```compile 'com.github.mjdev:libaums:0.5.5```

**Comment by SvenSv** [comment]
Sir, thank you so much.
(And of course there has to be a closing ' :
compile 'com.github.mjdev:libaums:0.5.5'
)
