### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by SvenSv** [magnusja/libaums#91]
Is there a complete javadoc somewhere?

**Comment by magnusja** [comment]
You mean online accessible?

Unfortunately not at the moment. I would suggest downloading the latest javadoc.jar from here https://bintray.com/mjdev/maven/libaums#files/com%2Fgithub%2Fmjdev%2Flibaums%2F0.5.5.

You can extract the jar file and then just open index.html

**Comment by magnusja** [comment]
Hey there,

just found this awesome website: [![Javadocs](https://www.javadoc.io/badge/com.github.mjdev/libaums.svg)](https://www.javadoc.io/doc/com.github.mjdev/libaums)
