### ISSUE TITLE
Copy file from USB Drive to internal storage?

### ISSUE THREAD

**Issue by nagesh-kashyap-r** [magnusja/libaums#92]
Hi,

How can i copy files on USB to internal storage keeping the file name same.

**Comment by magnusja** [comment]
Please have a look at the readme on the main page. It is explained how to list files, get file names and how to use InputStreams, which is basically all you need.
In addition, please have a look at my example application, which can copy from USB to internal storage.
https://github.com/magnusja/libaums/blob/develop/app/src/main/java/com/github/mjdev/libaums/usbfileman/MainActivity.java

**Comment by nagesh-kashyap-r** [comment]
Ok. Thanks 😊
