### ISSUE TITLE
Copy vs. Storage Access Framework vs. http server

### ISSUE THREAD

**Issue by SvenSv** [magnusja/libaums#93]
I'm writing an app that displays a lot of icons (.png) from an Usb-Stick. All icons together are like 2MB in size. Should I 
1) copy all files to the local storage of the smartphone
2) use the Storage Access Framework or
3) set up a http server?

I have the feeling this question doesn't count as an "issue" anymore. Should I write questions like this on here or are you somewhere else active, like stackoverflow?

**Comment by magnusja** [comment]
Hey @SvenSv,

yes in general StackOverflow is the better place to ask questions like this.

If you just want to show the icons in your app, it suffices to use the `UsbFileInputStream` like so: https://github.com/magnusja/libaums/blob/develop/app/src/main/java/com/github/mjdev/libaums/usbfileman/MainActivity.java#L310
This is also described on the main page in the readme.

If you feel like it takes too much time to read these files again every time, you can for sure cache these on the local storage to boost performance.

Hope that helps,
Magnus
