### ISSUE TITLE
Provider -XML - unresolved package 'storageprovider'

### ISSUE THREAD

**Issue by SvenSv** [magnusja/libaums#97]
After I added the XML-Tag from the readme / how to use -> Storage Access Framework section:

< provider
                android:name="com.github.mjdev.libaums.storageprovider.UsbDocumentProvider"
                android:authorities="com.github.mjdev.libaums.storageprovider.documents"
            android:exported="true"
            android:grantUriPermissions="true"
            android:permission="android.permission.MANAGE_DOCUMENTS"
            android:enabled="true"> 
            <intent-filter>
                <action android:name="android.content.action.DOCUMENTS_PROVIDER" />
            </intent-filter>
< /provider>

Andoid Studio complains about the first line: unresolved package 'storageprovider'.

What am I doing wrong? Thanks in advance.

**Comment by magnusja** [comment]
Did you install the storageprovider module?

**Comment by SvenSv** [comment]
I guess not, all I did was
compile 'com.github.mjdev:libaums:0.5.5'

How do I install the module?

**Comment by SvenSv** [comment]
...
compile 'com.github.mjdev:libaums-storageprovider:0.5.1'     ???
